[2023-11-03T13:28:09.135+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movies-etl-dag.write_to_es manual__2023-11-03T13:27:59.562781+00:00 [queued]>
[2023-11-03T13:28:09.152+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movies-etl-dag.write_to_es manual__2023-11-03T13:27:59.562781+00:00 [queued]>
[2023-11-03T13:28:09.152+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-11-03T13:28:09.170+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): write_to_es> on 2023-11-03 13:27:59.562781+00:00
[2023-11-03T13:28:09.176+0000] {standard_task_runner.py:57} INFO - Started process 2948 to run task
[2023-11-03T13:28:09.180+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movies-etl-dag', 'write_to_es', 'manual__2023-11-03T13:27:59.562781+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/movie_pg_es.py', '--cfg-path', '/tmp/tmpfdg3uxny']
[2023-11-03T13:28:09.184+0000] {standard_task_runner.py:85} INFO - Job 114: Subtask write_to_es
[2023-11-03T13:28:09.426+0000] {task_command.py:415} INFO - Running <TaskInstance: movies-etl-dag.write_to_es manual__2023-11-03T13:27:59.562781+00:00 [running]> on host e468bf2dfd15
[2023-11-03T13:28:09.848+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movies-etl-dag' AIRFLOW_CTX_TASK_ID='write_to_es' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T13:27:59.562781+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-03T13:27:59.562781+00:00'
[2023-11-03T13:28:09.912+0000] {movie_pg_es.py:118} INFO - [FilmWorkES(id='82297925-80cc-4c47-b6cf-6b5e06e23b70', title='Star Trek V: The Final Frontier', type='movie', rating=5.5, created_at=datetime.datetime(2021, 6, 16, 20, 14, 9, 223396, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2021, 6, 16, 20, 14, 9, 223412, tzinfo=TzInfo(UTC)), genre='Action, Adventure, Fantasy, Sci-Fi, Thriller', actors_names=['Leonard Nimoy', 'James Doohan', 'DeForest Kelley', 'William Shatner'], actors_ids=['5a3d0299-2df2-4070-9fda-65ff4dfa863c', '807ce9c3-6294-485c-803a-1975066f239f', '836bb95b-6db8-4418-a110-f41663b1c025', '9758b894-57d7-465d-b657-c5803dd5b7f7'], writers_names=['David Loughery', 'Harve Bennett', 'Gene Roddenberry', 'William Shatner'], writers_ids=['1a84b0ac-ff8f-4169-a14b-7393acea8ddd', '58411ec0-c40a-43da-95e3-0adc74b7e7f6', '6960e2ca-889f-41f5-b728-1e7313e54d6c', '9758b894-57d7-465d-b657-c5803dd5b7f7'], directors_names=['William Shatner'], directors_ids=['9758b894-57d7-465d-b657-c5803dd5b7f7'], description="When the newly-christened starship Enterprise's shakedown cruise goes poorly, Captain Kirk and crew put her into Spacedock for repairs. But an urgent mission interrupts their Earth-bound shore leave. A renegade Vulcan named Sybok has taken three ambassadors hostage on Nimbus III, the Planet of Galactic Peace. This event also attracts the attention of a Klingon captain who wants to make a name for himself and sets out to pursue the Enterprise. Sybok's ragtag army captures the Enterprise and takes her on a journey to the center of the galaxy in search of the Supreme Being."), FilmWorkES(id='de5347cf-a70d-430f-8005-786326e28794', title='Star Trek: Voyager', type='movie', rating=7.8, created_at=datetime.datetime(2021, 6, 16, 20, 14, 9, 223343, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2021, 6, 16, 20, 14, 9, 223360, tzinfo=TzInfo(UTC)), genre='Action, Adventure, Sci-Fi', actors_names=['Kate Mulgrew', 'Robert Beltran', 'Robert Duncan McNeill', 'Roxann Dawson'], actors_ids=['7f100195-5faf-4746-8a2b-df2a3e57cc8b', '83e09e52-4a63-49f9-8c34-3d09774f7509', 'c05da398-b37e-4993-8ad2-6bfd290c28ce', 'd58cfb85-fbec-46c4-b2ae-b9b87b9c8d70'], writers_names=['Rick Berman', 'Michael Piller', 'Jeri Taylor'], writers_ids=['88a99b4d-4d06-4754-b06c-93217cf53244', 'd67afc96-b9ed-4c91-9507-ffc2018c58d7', 'e3a8bf89-10a9-404a-8cd8-ea249c0a654e'], directors_names=[], directors_ids=[], description="The Federation starship USS Voyager, chasing a band of Maquis rebels, enters the dangerous space nebula known as the Badlands. Both ships are transported by a distant space probe to the Delta Quadrant, 75,000 light-years from Federation space. Voyager's crew and the Maquis form an uneasy truce to rescue crewmen of both ships, kidnapped by the probe's builder, the powerful, dying Caretaker. The Maquis ship is destroyed in a battle with the warlike Kazons. To prevent a Kazon aggression against a helpless world, Voyager destroys the space probe. Without the probe, it will take 75 years for Voyager to travel back to Federation space. With the differences between them rendered meaningless by time and distance, The Federation and Maquis crews unite aboard Voyager. Together, they embark on their new mission: to boldly go - home.")]
[2023-11-03T13:28:09.913+0000] {movie_pg_es.py:119} INFO - Processing 2 movie:
[2023-11-03T13:28:09.914+0000] {movie_pg_es.py:126} INFO - [{}, {}]
[2023-11-03T13:28:09.922+0000] {_transport.py:336} INFO - PUT http://movies_es_db:9200/_bulk [status:400 duration:0.006s]
[2023-11-03T13:28:09.922+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/movie_pg_es.py", line 127, in write_to_es
    helpers.bulk(es_conn, actions)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 291, in _process_bulk_chunk_error
    raise error
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 339, in _process_bulk_chunk
    resp = client.bulk(*args, operations=bulk_actions, **kwargs)  # type: ignore[arg-type]
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 704, in bulk
    return self.perform_request(  # type: ignore[return-value]
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: index is missing;2: index is missing;')
[2023-11-03T13:28:09.987+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=movies-etl-dag, task_id=write_to_es, execution_date=20231103T132759, start_date=20231103T132809, end_date=20231103T132809
[2023-11-03T13:28:10.010+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 114 for task write_to_es (BadRequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: index is missing;2: index is missing;'); 2948)
[2023-11-03T13:28:10.034+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-03T13:28:10.111+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
