[2023-11-03T13:21:14.895+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: es-schemas-creation-dag.create_es_index manual__2023-11-03T13:21:11.480284+00:00 [queued]>
[2023-11-03T13:21:14.905+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: es-schemas-creation-dag.create_es_index manual__2023-11-03T13:21:11.480284+00:00 [queued]>
[2023-11-03T13:21:14.906+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-11-03T13:21:14.926+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_es_index> on 2023-11-03 13:21:11.480284+00:00
[2023-11-03T13:21:14.933+0000] {standard_task_runner.py:57} INFO - Started process 2795 to run task
[2023-11-03T13:21:14.936+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'es-schemas-creation-dag', 'create_es_index', 'manual__2023-11-03T13:21:11.480284+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/create_es_indeces.py', '--cfg-path', '/tmp/tmpz3fkva20']
[2023-11-03T13:21:14.939+0000] {standard_task_runner.py:85} INFO - Job 98: Subtask create_es_index
[2023-11-03T13:21:15.173+0000] {task_command.py:415} INFO - Running <TaskInstance: es-schemas-creation-dag.create_es_index manual__2023-11-03T13:21:11.480284+00:00 [running]> on host e468bf2dfd15
[2023-11-03T13:21:15.553+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='es-schemas-creation-dag' AIRFLOW_CTX_TASK_ID='create_es_index' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T13:21:11.480284+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-03T13:21:11.480284+00:00'
[2023-11-03T13:21:15.980+0000] {_transport.py:336} INFO - PUT http://movies_es_db:9200/movies [status:400 duration:0.031s]
[2023-11-03T13:21:15.980+0000] {create_es_indeces.py:29} INFO - Ошибка создания индекса: [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/BpohD7qFTSqF5uh4OE4f9A] already exists', 'index_uuid': 'BpohD7qFTSqF5uh4OE4f9A', 'index': 'movies'}]
[2023-11-03T13:21:15.981+0000] {create_es_indeces.py:30} INFO - {'error': {'root_cause': [{'type': 'resource_already_exists_exception', 'reason': 'index [movies/BpohD7qFTSqF5uh4OE4f9A] already exists', 'index_uuid': 'BpohD7qFTSqF5uh4OE4f9A', 'index': 'movies'}], 'type': 'resource_already_exists_exception', 'reason': 'index [movies/BpohD7qFTSqF5uh4OE4f9A] already exists', 'index_uuid': 'BpohD7qFTSqF5uh4OE4f9A', 'index': 'movies'}, 'status': 400}
[2023-11-03T13:21:15.981+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-03T13:21:16.035+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=es-schemas-creation-dag, task_id=create_es_index, execution_date=20231103T132111, start_date=20231103T132114, end_date=20231103T132116
[2023-11-03T13:21:16.071+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-03T13:21:16.139+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
